// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unohdmxakvaotyyfzucg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVub2hkbXhha3Zhb3R5eWZ6dWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3MjczOTYsImV4cCI6MjA4MzMwMzM5Nn0.S-t9JUPWSjs3ghZTX831ZI86r_lnZo5nW5dCz3Ems4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});