// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://artyddpgtnbkdyybponr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFydHlkZHBndG5ia2R5eWJwb25yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzODQzNjIsImV4cCI6MjA3NTk2MDM2Mn0.S9L7zFmmbUzZVl8kBO9ld7x4ShJFUZvkbeg_W6VJnjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});